name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]  # или master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Получение кода
      uses: actions/checkout@v3

    - name: Установка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Запуск тестов
      run: |
        pytest tests/

    - name: Деплой на сервер
      if: success()  # Только если тесты прошли
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/myapp
          git pull origin main
          systemctl restart myapp
